language: node_js
node_js:
  - "0.10"

env:
  global:
    - secure: "C84pbYIZRPUnyXw07sVUlY4hP3Di1JjFAhxFD/HzwOFbi8xRW+/TxJUasTy0wt/CwQhH+lcCN7DGGX7fOIph0J/DGx5r+7cfNFnoLmeXoQHz+24cqHbEcyn8yntjJTJnM
HWJ8GuMWmbFTcrfKily6UlN7oVvqcEWi4fNds+8BaE="

branches:
  only:
    - master

install:
  - npm install serve-static finalhandler
  - cd browser-tests && npm install && cd ..

script:
 - chmod -R 777 ./ci-release.sh
 - ./ci-release.sh
