#!/bin/bash

    # set default if launching this on developer's machine
    TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG:-ariatemplates/hashspace-todomvc}

    # gitignore is needed for developer to not commit "min" files to "master"
    # deleting it on Travis to be able to commit to "gh-pages"
    if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then
        rm architecture-examples/.gitignore
    fi
    cd architecture-examples/hashspace/min &&
    echo "Installing gulp and other build dependencies..." &&
        npm install -g gulp@3.8 &&
        npm install &&
    echo "Building minified version of hashspace-todomvc..." &&
        gulp &&
        cd - &&
    echo "Installing test suite dependencies..." &&
        npm install serve-static finalhandler &&
        cd browser-tests && npm install && cd .. &&
    echo "Starting the phantomjs suite for hashspace and hashspace-min..." &&
        node test &&
    echo "Cloning gh-pages..." &&
        git clone "https://github.com/${TRAVIS_REPO_SLUG}.git" -b gh-pages gh-pages &&
    echo "Cleaning up gh-pages..." &&
        # cleanup current content of gh-pages, copy new stuff from "master" to "gh-pages"
        rm -rf gh-pages/architecture-examples &&
        mkdir -p gh-pages/architecture-examples &&
    echo "Copying new content to gh-pages..." &&
        cp -rf architecture-examples/* gh-pages/architecture-examples &&
        cp ./{index.html,learn.json,.gitattributes,.gitignore} gh-pages